# .github/workflows/release.yml
name: Create Release

on:
  push:
    tags:
      - 'v*'  # Se déclenche quand tu push un tag comme v1.0.0

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Zip src folder
        run: zip -r release-${{ github.ref_name }}.zip src/

      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          files: release-${{ github.ref_name }}.zip